import HashMap from "./hashmap.js";

const test = new HashMap();

test.set("apple", "red");
test.set("banana", "yellow");
test.set("carrot", "orange");
test.set("dog", "brown");
test.set("elephant", "gray");
test.set("frog", "green");
test.set("grape", "purple");
test.set("hat", "black");
test.set("ice cream", "white");
test.set("jacket", "blue");
test.set("kite", "pink");
test.set("lion", "golden");
test.set("jacket", "white");
test.set("kite", "grey");
test.set("lion", "brown");
test.set("moon", "silver");
test.set("banana", "pink");
test.set("carrot", "blue");
test.set("dog", "green");
console.log(test.length());
console.log(test.get("dog"));
console.log(test.get("hmm"));
console.log(test.remove("dog"));
console.log(test.remove("hmm"));
console.log(test.has("dog"));
console.log(test.has("hmmmmm"));
console.log(test.keys());
console.log(test.values());
console.log(test.entries());
